# Generated by Django 5.1.1 on 2024-12-02 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admin",
            name="admin_id",
        ),
    ]
