# Generated by Django 5.1.1 on 2024-12-02 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0002_remove_admin_admin_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="students",
            field=models.ManyToManyField(
                related_name="is_student", to="e_learning.student"
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_teacher",
                        to="e_learning.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("course_content", models.TextField(blank=True)),
                ("course_documents", models.FileField(upload_to="course_documents/")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_course",
                        to="e_learning.subject",
                    ),
                ),
            ],
        ),
    ]
