# Generated by Django 5.1.1 on 2024-12-02 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0003_teacher_students_subject_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="subject",
        ),
        migrations.AddField(
            model_name="course",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_image/"),
        ),
        migrations.AddField(
            model_name="subject",
            name="course",
            field=models.ManyToManyField(
                related_name="course_subject", to="e_learning.course"
            ),
        ),
    ]
