# Generated by Django 5.1.1 on 2024-12-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0004_remove_course_subject_course_course_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="subject_description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_documents",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="e_learning/static/e_learning/course_documents/",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="e_learning/static/e_learning/course_img/",
            ),
        ),
    ]
