# Generated by Django 5.1.1 on 2024-12-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0005_subject_subject_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="course_documents",
            field=models.FileField(blank=True, null=True, upload_to="documents/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_image",
            field=models.ImageField(blank=True, null=True, upload_to="img/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="subject_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
