# Generated by Django 5.1.1 on 2024-12-11 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0006_alter_course_course_documents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="enroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stud",
                        to="e_learning.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subje",
                        to="e_learning.subject",
                    ),
                ),
            ],
            options={
                "unique_together": {("student", "subject")},
            },
        ),
        migrations.AddField(
            model_name="subject",
            name="enrolled_by",
            field=models.ManyToManyField(
                related_name="enrolled_sub",
                through="e_learning.enroll",
                to="e_learning.student",
            ),
        ),
    ]
