# Generated by Django 5.1.1 on 2024-12-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0008_opened_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opened_course",
            name="is_open",
        ),
        migrations.AddField(
            model_name="course",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
