# Generated by Django 5.1.1 on 2024-12-13 01:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0009_remove_opened_course_is_open_course_is_open"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="is_open",
        ),
        migrations.AddField(
            model_name="opened_course",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
