# Generated by Django 5.1.1 on 2024-12-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0010_remove_course_is_open_opened_course_is_open"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_open",
            field=models.BooleanField(default=False),
        ),
    ]
