# Generated by Django 5.1.1 on 2024-12-14 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0012_comments"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="student",
        ),
        migrations.RemoveField(
            model_name="comments",
            name="subject",
        ),
        migrations.AddField(
            model_name="comments",
            name="course",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_comments",
                to="e_learning.course",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comments",
            name="user",
            field=models.ForeignKey(
                default=11,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_comments",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
