# Generated by Django 5.1.1 on 2024-12-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0013_remove_comments_student_remove_comments_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="comment",
            field=models.TextField(),
        ),
    ]
