# Generated by Django 5.1.1 on 2024-12-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("e_learning", "0016_student_profil_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="admin",
            name="profil_img",
            field=models.ImageField(blank=True, null=True, upload_to="img_profile/"),
        ),
        migrations.AddField(
            model_name="teacher",
            name="profil_img",
            field=models.ImageField(blank=True, null=True, upload_to="img_profile/"),
        ),
    ]
